export const ADD_TO_GOAL_ARR = 'ADD_TO_GOAL_ARR';
export const UPDATE_GOAL_ARR = 'UPDATE_GOAL_ARR';
export const ADD_TO_METRIC_ARR = 'ADD_TO_METRIC_ARR';
export const UPDATE_METRIC_ARR = 'UPDATE_METRIC_ARR';